server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Compression GZIP pour améliorer les performances réseau
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Si le fichier/dossier demandé n'existe pas, renvoyer index.html
        try_files $uri $uri/ /index.html;
    }
}
